---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgC51dKd44zeQdVtR+aezQ9uRE65I6M/g/epMVxW2vNjLT7G8ANNW76+tmuoaANSnbb1DTUkixOcZ9UI00AKfJSl0Chr++Hpq7PbdMrwnWa587DNokFRKI6Lq6/flmwsMaxIsGqF+Q29kSyTE7irk8+oX/IYbnEcf6l2AkQ4718vyc4SiwuAPWnF7jZ4FZVUmUBbaigR7vMOP33oMXGUiM3LaX1TosAjD+58QmQ2MrqMBZOwkxppGhoiib2eR2Ur+K8emybLSYYiGM7nkvi7FHJUkJ0V9W1pDm0fk4n8lPZqYY0SiD5cipiNO0hndBbb7UaJBkxKrQaAh23o2UQnybQ8kI6IxNB9qznyKE8E583UNhwc6Otaswh08LP+Jtd3ALuLEyfnqCJl/DCaP4HWlUu6C9H+bentmK06yHiI4pRnYo/x18se4Afmh5qYxphNSIA9ub4G1LQBx2Tj93sut4+kfedjVnOwj64+sJqrg3WqVTrFEha9Ec0nJmIHFGI2FCvNNMfG0EmdDooGKFTRSbX/L4FbSdY575QQV14Aoun+CTAo3CF2mZ11owonaJpP61WjyzsR3TknPxy+C1ynqnh/YsTH9vKVoUkip9aUmxGu4KAxqCHydskCHE1UVxXaegS5gTmBBbU092wnXHvP76iVcYVALtW9fT/S/vUyoFhrswnD8CvakuIpDrWah6TxeZUc5Ofn61qgFyPiCfmYjavif/0W2eXNjRd8L4IXHqdIlmlg4EbxZZBLkZCHKf9dpbEJTFoSK9bKbtuzfM/pBWuBHrDWETybMLQuHOomhYjGTmoG6B4FdjGB8mlKA36Z9l3yQf89p5yLnep/lG/ulDzlEXTBzD2iTehcoXDI9Hpsl9SxKCzvny6Ld3jABFBjY0QHakNA5FnISr94Z7EB4TdN+uMcz+LJZYPmuLx9j3MkaIaieunlIOAM
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared 
