---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBUNgItlOrn0uNAR1bp1x62cubXphzB/5bjLeoryYfzKZgw0ikCfzkFzzIYA29CRPUGkPDwhMuD2MJw0cjlBGXKxiyet8TMaD/8v1wJpyGU0LH0g+2bJRhgP4o3zdJLL9NiahY5QOCYJ8Gespsml06k2F6Ka17CFInK2oVBthyCmILsBo3NvUHM5qgHVnwhJaTNKHT19ZgMUjd9EQwKtahaKYYqjOYrb/TkZzBpt0LoPN3LUfxr5afCiXUdjlpsV9ZTtq3mwcrRgNWuGpw5FvYSZcFrVOxvEnyDANTpIQ5P5yqIzYqwczeBqe8gakeiNh7GSX44hx1M1/hm4Klo+EAFCBCbQXNujH29+h8rk/8hTDiyz9vOtsxfE2b7SUdBpYO9IQt2dRG8zEalryNvutHLBe89pbW3E3TKLG+fj4HdxGvRpdYrLyF5cEf3yJD+x3wIHxz7L6CKTo3Vb1BgLz/u4rTku3SOrN9DMcoIrEGYgeo1knTB3FiYZQa98+y4W/uMXXRANTB85iloAhyusPOzOUYoq0T7NiqkB8Krxpfb+RPwlvH2mnnza+nWKRY8raNUyhWJ6NfsXpX6j8Avt3O6EwZ3fjrIucnje2AXphLFdRAhld33Mhvt/9ZAtI7sagyY4OOsBjpPmgEXbhv09gH5Fx+71erBDg6t7BtOdEg6OZrsgX/OznT6vXlV0qC9qIfWnkZekpAbgr+HmUJSwKm69Kr6KAQ8Do5ij/DJ8yi5us7yeOmBv7u7WYseeboAcONM04Yl4CCqRzqsaIJn5MSzZD7bm715b4BO53LKElctHJYirH7vWyKCH7UENLQ+429WoPS823uTbuxgG5rtlIwgNhNjBwDIFjay3tWNWtX6+QsqmuBKXWdL9DVTKOBKdtCKVGlA9nctTi6GKPuhFEXp1v4O7rVyNvQy+lfRyPvmYvZEaAxnkJ9uEgo+qh36qqh9fj1NdQorgbnc5B4XXarRg5yN+uNYNvDuexvJdVhdZfuqiaMO5WzpJc+x2kx2ngWCahfSTWHTNw==
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
