---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBj2h2wV41QX5xHM287ucHk0UeEAjzjpqQ6MJlmexSS9SiahYH1eC/HbZTPkAxouoeJ7FK8jaWG9maqDPFvE8q3Ee1S2aJ+PZPvbziSxw3xw40LTVtOV3sN5bBhs7eOF2ERiPATVPhpKREC2ndF7UEWfUhFB/o7Ag3dakZ4yCP5K4T1Prvo4hsTjF5rkKbqxQ5yJ2TjvJZFXDP2YgiEepSNaJrtRjm4T8UU55mnLBnE4PSmeOotVX1EyT1r+u7DmcMMGd7uA0a7UdpU9uda3z+qWLrc5mrH6KkXWGBAn2+O15SfaPZ19sSNqA/nKnNszWt1w8IlhAIOc0tXaj3/HNLUmWik2WB13hlH4oZzpH5G9va8vJY4YlTTHyZ45F+ZxWAAOMyYAkCJ2SlZsJ9Q4KgSuQBi6+YGCdqmb6+OD+tM85gYYzaAPLHOIKfx7BuMqFtdQikrfe8BexXfvwy9ySqAKOd6TBMToH2Un8tjswpiKHw8zK0Bw01AarF5xYq5WbBbZedoUXpQsgm9Vnsyt3cgY8I7BxhcW2ScPihZmiWX3KdEcHR0aDP+tLQIerD5WdofrdpQB9vIHcvEMR8BdQKeFOSqZAqEwXHbM9/wRSFUvLIIRRVS8YP3x+TY4YPtqruk86Imwfu4j5noxttiS8WPw9Nh1j0oVLvtEHnmABlmbUv6Qv7HiQAI81a5IoYmnh3kGj34VTkGnB0pk/I935XBSENmICtrd9GjPlqoOzeRirgnX9ZfbwwfuYhyhwag/L/N+kzywlVd6WFscuNMBzNS1gi5TKZoLbxSnbPH6/gKS8EXZgRITyDxSL8f4Nqa51c+zrMse1rNbkeiZeyQM+ZC49mHRATlwNJR+6KG2JDrB/wSL/PkC5gFX3yc2VEPapH93y2OTqSRHlN7j8Io4C8sOwf0kdDRrIkLRGUf3RgpVk/KizLHQRe+
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
