apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/traefik
patches:
  - patch: |-
      - op: add
        path: /spec/values/service
        value:
          type: NodePort
          nodePorts:
            http: 30080
            https: 30443
      - op: replace
        path: /spec/values/dashboard/enabled
        value: true
      - op: add
        path: /spec/values/ingressRoute
        value:
          dashboard:
            enabled: true
            # expose dashboard at traefik.staging.local
            entryPoints: ["web"]
            matchRule: Host(`traefik.staging.local`)
    target:
      kind: HelmRelease
      name: traefik
