---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-container
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCnWpgDeb8lZplbzBfQFxmuFnfYoPmmo+O8cvGZyS2a04E85FP3N42Wn8CySyRhy26w95j7GkTQrXMNoaLueL038Vr7ihupYFna2lUVQDc4KG+ufLKrZKwlI9k4bBz92o+2pjqbFzbQsWrEAnAuBe83CWkb7oAx+pOD4a5ab+4JuLHQ46/KbLQ7kuo8PNJsPIZbFmkGkQER3Bw9tc8/lg+WIKemtEPxxPrLJQNNvvdmPC+IA2GJeNpGEsJTA0t/8itdDDdmVSfVUHaOWdWJD+iqAkE3kpuSQ4yFE5C32qiyBA49xvu1azAzdhZLDWKlwG3H7jADMtHPAqGfd4i88AVBghHKxpsedoooxOcrTe3ekOnc5K7UccEWECt7EGZYJOEH1Frp8m0zwAgqbSZZJ8rR1b3KLRYBUxkjBsm2EuAgZqY76+G3ZGerqtl3LbsCqMGMqXB2FAnNrwWsg0dPu6Xs4uXbm6lhDDN6loqASCSzTtl72MWpuxI9kyigI2gWslTeVWHObj4M+BbDJrla959av499tWHplWR57YMLefHiAMKk9qbwp08XDtYAjah962cVTkojT2xTpZpamCosUN/TZLqxyhf1GfOazCs6h31yoeGnejTeCkTZF5PTMumW/qoySh6F0Bf1T4nqyrPSu0IgtbaebZzd8DbgtyxvoAJqyNH2lzCByqMvEHWsCVe+QMbjqSxw3ZV7Srk6iDnc78dyMcKtz6p1+6uox/GM5+FXEjKuktaBNslp
  template:
    metadata:
      name: renovate-container
      namespace: renovate
